= Yupiik BundleBee

image:https://img.shields.io/maven-central/v/io.yupiik/bundlebee?color=00b2ef&label=Last%20Release&logoColor=00b2ef&logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAACAAAAAqCAYAAADS4VmSAAAAAXNSR0IArs4c6QAABGdJREFUWEedmF2I3FQUx%2F9nZrYzq7ttMtuK32B90WpFEbtUW2T7UqqbjIgM%2BKQP%2BmAfBUEFP0H7oo%2BiIgg%2BqRUqk%2BwWRXTFj9UWoVIp7UN1H9QitTvJMtpOd3dydDI7k9zk3syd5C25557zO1%2F3I4S8z3xzJzp0MpweBDfioanf86iiPJPCOY7HwlzbzKUr1yQ4XgAgOZdhm4VRHcoLIHrft5ojCqMDiKF%2FGlQkcOfNgecjQowGcKS5ByX6NmUsDrXOe%2FFw9TvdVIwGEDdUNiawn%2F4NDR0%2BP4HKWCtPFPQBXP8EmO9UGonDEf0My7hLJwr6AHEDqjzryCSo9ACEtuM%2FYVevl3rneH8D2LoxptWWugBR2w2r8hGjMBxAaDt6BrbxRmZuHf81gJ%2FXLchsgEbzQRDN6SobyMWhmWdRq86roLMB4ooKVMWs4Q0Uuf4jYP4kfKfONKytxwdjR1vbsL5%2BXgdcDeD6J8G8U6vtukLJ2hDb8hdYxh2yKKgBsorJ9QJwYjMiMKzEZqRRkHKAhrcKwliPmC7ANrYN6A%2Bf2oTKtZelOW1%2FUUK93oml6RKYK%2BE7Yw01c1NyXhpggSto%2BZe0Qh%2FgMQBFFPC%2BlvykMY4Zasch0gBC4RUfx%2BzmDwYT5lem0Ql%2BTBkTWjW4HfbUqVhHvALgRRWgCDDXmkGw%2FpWWN%2BXLE9h%2FdW8z%2BtQzUETUIVkFWSjtw%2BzkQt%2BGCBD3pG2UUKcon43mCRBpbkZYhGXeF9UNj6PiX5Q5FgE4zUWAdmt5n2czEtLEP8Cu3huWeCxX6vVenHwadnWHtAsc7zcAN43iRA9gmAGNftZ05A8A18UBCQtcQstf06JmfhS16kdS7%2FsfHf9ZgA9p6Zs0xkjwngsHUNvyWeTNch0ofKxUpiIRNiO6BzXjp4Fow38OxK9HXZC8YDAfRK36dio1JaOCB0i%2BAiZBjvx1FcbKn8MyxWOZ670MxkviQuR4vwLYnnKG2QeRsfG9A9ssZYY%2Ba9BpXgRoPCVCWOwVoXvhFnDxtFLHsFOQTirS1rfDNpbSS3HD64Agv2JR8VZYm88MKcJ9AH8plWEEqJlFMQVq%2Bq8B3K8Y%2Fga2KY45XrfQ7s6Ea%2F9zBeo3RBud5IIJzPmmePJZ2QUOjuXKf6GzA0FpL8DvqjpJTIG7%2FCq48EIoTPQULOMdwXCyY%2BRU6eO4cDrCDCyzG92eGaUBWeE5%2FlsAH8yMBvMh1KrRqbgvrFhNIwDXOwfGNdJQOZ4PYMtIaWAso2b2LynJHxrHYZvTsQgwwfG7Px16T9f7bi0E3FQbDZ4ECu%2BF490lmuhDpWz%2FIiuJgmQzoiWAox1N1LoK2yyHn5zlJ2IA0dnf9dfArFq0ugeYK%2BOOSgAkfhBcWKYt1osCoC%2Fk%2BsfAvCszbbZJQwCC3bCnojNgXJsqAkmLzsoBIDgqBRkAuP5ZMN88EGqfK6N%2B22omvS5AX8nCUgUtI74IfQ%2Fb3DP8cqqiGBVAoSc%2FQFiIG%2F8K825W%2F%2Bv4D2sg4qMfRFPFAAAAAElFTkSuQmCC[]
image:https://github.com/yupiik/bundlebee/actions/workflows/maven.yml/badge.svg?branch=master[Github CI]
image:https://img.shields.io/github/license/yupiik/bundlebee.svg[License]

Yupiik Bundlebee is a powerful, lightweight tool designed to simplify Kubernetes deployments and resource management by packaging Kubernetes manifests into easily reusable and maintainable bundles.

== 🚀 Key Features

- **Reusable Bundles**: Package Kubernetes resources into reusable bundles for simplified management.
- **Declarative Configuration**: Define application deployments and Kubernetes resources clearly and simply.
- **Variable Substitution & Templating**: Easily customize bundles dynamically based on deployment environments.
- **Flexible Deployment**: Deploy Kubernetes manifests selectively or entirely in one simple command.
- **Integrates with Kubernetes**: Seamlessly integrates with standard Kubernetes tools and workflows.
- **CLI & Automation Friendly**: Simple yet powerful command-line interface for automation and scripting.

In Bundlebee, a bundle is called an `alveoli`.

== 📦 Installation

Quickly install Bundlebee using the provided installer:

[source,bash]
----
curl -L https://yupiik.github.io/bundlebee/install/install.sh
bundlebee version
----

Or use it directly from your Maven project:

[source,xml]
----
<dependency>
    <groupId>io.yupiik.bundlebee</groupId>
    <artifactId>bundlebee-core</artifactId>
    <version>1.0.29</version>
</dependency>
----

== 📖 Quickstart

🌐 https://www.yupiik.io/bundlebee/getting-started.html

== 🛠️ Useful Commands

- Deploy resources:
[source,bash]
----
bundlebee apply --alveolus=my-bundle
----

- List available bundles:
[source,bash]
----
bundlebee list
----

- Inspect resource details:
[source,bash]
----
bundlebee inspect --alveolus=my-bundle
----

- Remove resources:
[source,bash]
----
bundlebee delete --alveolus=my-bundle
----

== 📖 Documentation

Comprehensive documentation is available at:

🌐 https://www.yupiik.io/bundlebee/

You can see a full example of deployment in the Yupiik Fusion example project:

🌐 https://github.com/yupiik/fusion-examples/tree/main/app-deployment

== 🖥️ Contributing

We warmly welcome contributions!

- Fork the repository
- Submit your enhancements via pull requests
- Create https://github.com/yupiik/bundlebee/issues[issues]
- Open https://github.com/yupiik/bundlebee/discussions[discussions]

=== Build

Pre-requisite: Apache Maven >= 3.8 and Java >= 17.

== 📜 License

Yupiik Bundlebee is released under the Apache License, Version 2.0. See the LICENSE file for more details.

== ©️ Copyright
Copyright © 2025 Yupiik.

🌟 *Simplify your Java applications deployment with Yupiik Bundlebee.* 🌟
