#
# Copyright (c) 2021 - present - Yupiik SAS - https://www.yupiik.com
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-server-daemonset
  labels:
    app: loki-simple
    app.loki: promtail
  namespace: "{{loki-simple.namespace:-{{bundlebee-kubernetes-namespace}}}}"
spec:
  selector:
    matchLabels:
      app.loki: promtail
  template:
    metadata:
      labels:
        app: loki-simple
        app.loki: promtail
    spec:
      serviceAccountName: promtail-serviceaccount
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: run
          hostPath:
            path: /run/promtail
        - hostPath:
            path: /var/lib/docker/containers
          name: containers
        - hostPath:
            path: /var/log/pods
          name: pods
      containers:
        - name: promtail-container
          image: {{loki-simple.promtail.image:-grafana/promtail:2.8.2}}
          args:
            - -config.file=/etc/promtail/promtail.yaml
          ports:
            - containerPort: 3101
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: run
              mountPath: /run/promtail
            - name: containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: pods
              mountPath: /var/log/pods
              readOnly: true
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: {{loki-simple.resources.limits.cpu:-0.2}}
              memory: {{loki-simple.resources.limits.memory:-128Mi}}
            requests:
              cpu: {{loki-simple.resources.requests.cpu:-0.1}}
              memory: {{loki-simple.resources.requests.memory:-64Mi}}
