#
# Copyright (c) 2021 - present - Yupiik SAS - https://www.yupiik.com
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-local
  labels:
    app: kafka-local
spec:
  serviceName: "kafka-local"
  replicas: 1
  selector:
    matchLabels:
      app: kafka-local
  template:
    metadata:
      labels:
        app: kafka-local
    spec:
      initContainers:
        - name: chmod-kafka-data-folder-workaround
          image: alpine:latest
          command:
            - chown
            - -R
            - 1000:1000
            - /usr/share/kafka/data
          volumeMounts:
            - name: pv-data
              mountPath: /usr/share/kafka/data
      containers:
        - name: kafka
          image: "{{kafka-local.image:-apache/kafka:3.8.0}}"
          envFrom:
            - configMapRef:
                name: kafka-local-config
          ports:
            - containerPort: 9092
              name: kafka
          volumeMounts:
            - name: pv-data
              mountPath: /usr/share/kafka/data
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: kafka-pv-claim
