= How it works
:minisite-index: 200
:minisite-index-title: How it works
:minisite-index-description: How BundleBee works.
:minisite-index-icon: car-battery

[abstract]
BundleBee is a light Java package manager for Kubernetes applications.
This page explains how to get started with it.

== Overall architecture

One of the BundleBee goals is to inherit from the well known and supported Apache Maven infrastructure.
In other words, the goal is to be able to reuse Maven registries (central, custom nexus, artifactory, ...) to store application descriptors.
It also leverage the well know java packaging (jar or zip) to ensure a strong storage reliability in these systems.

One direct benefit is that it becomes very easy to have an immutable system once deployed and therefore a better tracability of what is deployed.

Overall, BundleBee will manipulate what we call `alveolus` which are basically just a set of descriptors.
An `alveolus` is a zip or a jar which is structured this way:

[source]
----
.root
 `- bundlebee <1>
      |- manifest.json <2>
      `- kubernetes <3>
           |- my-descriptor-1.yaml
           `- my-descriptor-2.yaml
----

<.> A `bundlebee` folder contains all the descriptors
<.> A `manifest.json` contains the list of application or library this alveolus provides
<.> A `kubenetes` folder contains the list of descriptors used by alveoli

== Manifest

Manifest is the central point of the system.
It provides the unique identifier of your recipe (application/library) and what to do to set it up.

Here is its configuration specification:

include::content/_partials/generated/jsonschema/manifest.descriptor.adoc[leveloffset=+2]

TIP: manifest content can be wrapped in a `bundlebee` key (you wrap the whole content) which enables you to add other metadata in the manifest and still reuse BundleeBee JSON-Schema for the validation (by composition).

=== JSON-Schema

If you use JSON-Schema facilities in your preferred editor, here is the raw JSON-Schema for the manifest descriptor:

[source,json]
----
include::content/_partials/generated/jsonschema/manifest.descriptor.json[]
----

TIP: you can also use last version from link:https://raw.githubusercontent.com/yupiik/bundlebee/gh-pages/generated/jsonschema/manifest.descriptor.json[this link].

== Deployment and Dependency Management

A manifest can reference descriptors in other alveoli, it just requires to reference them to let bundlebee find them.

There are mainly two ways to deploy an alveolus:

. Classpath mode: you put all your zip/jar in the classpath. This mode requires there is no conflict between descriptor names (which is the recommended practise) and it will never look for external descriptors.
It is typically a recommended mode to avoid network I/O except with the Kubernetes cluster.
. Fetch mode: in this mode, a missing descriptor in the classpath will look for `descriptor.location` and lookup the jar/zip referenced by this location (generally a maven coordinate in the form `groupId:artifactId:version`).
It will first use your local Maven repository but can download the jar/zip if missing locally.
Then the jar/zip is read and descriptors are looked up from there.
This mode is nicer when depending on a lot of external alveoli but requires I/O to grab the dependencies.

== Customize descriptors

Indeed, you can bundle all your stack and hardcode your configuration or create one alveolus per environment.
This is one option which works well and enable to version its configuration.

However, for testing purposes, it is also neat to be able to patch descriptors on the fly.
For that you can use `descriptor.patches` in the manifest which will transitively enable to patch the descriptors - even the ones you don't own - using JSON-Patch and interpolations.

Here are some examples.

[source,json]
.Patch using CLI option
----
{
  "alveoli": [
    {
      "name": "com.company.alveoli:my-app:${project.version}",
      "descriptors": [
        {
          "name": "com.company.alveoli_my-app.configmap"
        },
        // ...
      ],
      "patches": [ <1>
        "descriptorName": "com.company.other_alveolus.configmap", <2>
        "interpolate": true, <3>
        "patch": [ <4>
          {
            "op": "replace",
            "path": "data",
            "value": {
              "my.config.value": "{{my.arg:-defaultValue}}" <5>
            }
          }
        ]
      ]
    }
  ]
}
----

<.> We add to the alveolus a list of patches to apply on some descriptors
<.> We reference the descriptor to patch
<.> We enable interpolation from Microprofile Config (which include CLI args)
<.> We define the JSON-Patch to use (optional, interpolation will also interpolate the descriptor if designed to be interpolated)
<.> We use an interpolation in the configuration in the JSON-Patch `replace` operation which replaces the data of the referenced `ConfigMap`

TIP: this mecanism is very useful for `ConfigMap` descriptors but also `PersistenceVolume` since you can now patch `/spec/hostPath `easily too.

== Deploy a dependency (or descriptor) conditionally

In some case it can be neat to be able to not deploy part of the stack.
It is typically the case when you wrote a monitoring-full alveolus (ie with some optional services functionally).
In such a case you can condition dependencies and descriptor deployment:

[source,json]
.Deploy monitoring alveolus only if MONITORING option is set
----
{
  "alveoli": [
    {
      "name": "com.company.alveoli:my-app:${project.version}",
      "dependencies": [
        {
          "name": "io.yupiik.alveoli:monitoring-alveolus:${bundlebee.version}",
          "location": "io.yupiik.alveoli:monitoring-alveolus:${bundlebee.version}",
          "includeIf": {
            "conditions": [{
              "key": "MONITORING",
              "value": "true"
            }]
          }
        }
      ]
    }
  ]
}
----

TIP: used on descriptors and using a complete set of conditions for descriptors you can handle environments this way (`ENV=preprod` for descriptor `preprod.configmap` for example).

== Filter manifest at command time

In some case it can be needed to evaluate some values of the manifest when executing the command.
Even if not recommended it can be done using `{{xxx}}` placeholders - read from environment variables and system properties.

[source,json]
.Filter manifest.json at command time
----
{
  "alveoli": [
    {
      "name": "com.company.alveoli:my-app:{{project.version}}",
      "dependencies": [
        {
          "name": "io.yupiik.alveoli:monitoring-alveolus:{{bundlebee.version}}",
          "location": "io.yupiik.alveoli:monitoring-alveolus:{{bundlebee.version}}"
        }
      ]
    }
  ]
}
----

With this manifest you can value `project.version` and `bundlebee.version` using the command line:

[source,bash]
----
bundlebee \
    [your command and options] \
    --project.version 1.2.1 \
    --bundlebee.version 1.0.1
----

=== More placeholders

Placeholders can use some keywords to get some particular values:

- `bundlebee-strip:<value>`: strips the provided value,
- `bundlebee-strip-leading:<value>`: strips the provided value at the beginning,
- `bundlebee-strip-trailing:<value>`: strips the provided value at the end,
- `bundlebee-indent:<indent size>:<value>`: indents a value with the provided space size, it is generally combined with another interpolation (file ones in particular) as value, ex `{{bundlebee-indent:8:{{bundlebee-inline-file:myfile.txt}}}}`,
- `bundlebee-inline-file:<file path>`: load the file content as value,
- `bundlebee-base64-file:<file path>`: converts the file in base64 (useful to write `data:xxxx,<base64>` values for ex keeping the raw file in the filesystem, very helpful for images),
- `bundlebee-base64:<text>`: encodes in base64 the text,
- `bundlebee-digest:BASE64|HEX,<algorithm>,<text>`: computes the digest of the text encoded in base64 or hexa format (useful to read files like `ConfigMap` or `Secret` and inject their digest value in a `Deployment` annotations to force its reload for example),
- `bundlebee-quote-escaped-inline-file:<file path>`: load the file content as a quoted value,
- `bundlebee-json-inline-file:<file path>`: load the file content as a JSON string value - without quotes,
- `bundlebee-json-string:content`: escapes a string to be a JSON string (useful when you inject with `bundlebee-json-inline-file` a string in another string like in JSON `ConfigMap` in a JSON configuration),
- `bundlebee-maven-server-username:<server id>`: extract from your maven `settings.xml` a server username (see configuration for a custom settings.xml location),
- `bundlebee-maven-server-password:<server id>`: extract from your maven `settings.xml` a server password (potentially deciphered),
- `bundlebee-decipher`: use Maven ciphering logic (`AES/CBC/PKCS5Padding`) to read a clear value. Syntax is as follow `{{bundlebee-decipher:$masterKey,$cipheredValue}}` with `masterKey` another *placeholder* name which contains the master key and `cipheredValue` the value to decipher. Indeed we recommend to reference the master key with another shared placeholder if you use a single one (`{{bundlebee-decipher:{{myMasyterKey}},$cipheredValue}}`). Last, since the value will be surrounded by `{` and `}`, we tolerate spaces before/after to avoid any confusion with the mustable like syntax we use for placeholders: `{{bundlebee-decipher:{{my.master.key}}, {...base64....} }}`,
- `bundlebee-kubernetes-namespace`: the Kubernetes namespace defined in the HttpKubeClient,
- `kubeconfig.cluster.<cluster name>.ip`: extract cluster IP from your kubeconfig,
- `timestamp`: current time in milliseconds (since epoch),
- `timestampSec`: current time in seconds (since epoch),
- `now`: `OffsetDateTime.now()` value,
- `date:<pattern>`: format `OffsetDateTime.now()` value using the provided pattern,
- `nowUTC`: `OffsetDateTime.now()` value with UTC `ZoneId`,
- `kubernetes.<namespace>.serviceaccount.<account name>.secrets.<secret name prefix>.data.<entry name>[.<timeout in seconds>]`: secret value looked up through Kubernetes API.
- `jsr223:<script path as file or resource or inline script>`: executes a JSR223 script to get the result, assumes that the script engine implementation is available in the JVM (not by default). To find the engine it uses the file extension or a comment in the file (for inline script) containing `bundlebee.language: <lang>`. The script contains the two functions `lookupByName` and `lookupByType` which can lookup a CDI bean to reuse BundleBee utilities (ex: `const bean = lookupByType.apply(getType('io.yupiik.bundlebee.core.kube.KubeClient'))`). If no language is found it defaults on `js`.
- `bundlebee-directory-json-key-value-pairs:/path/to/dir`: creates a JSON object from a directory. The path can be either a directory path of a directory path with a glob pattern at the end (`/path/to/dir/*.txt` for example). The keys are the filenames (simple) and `____` are converted to `/`. The values are the content of the files, filtered. Note it only works with exploded folders, not jar resources as of today.
- `bundlebee-directory-json-key-value-pairs-content:/path/to/dir`: same as `bundlebee-directory-json-key-value-pairs` but dropping enclosing brackets to be able to embed the content in an existing object (like `annotations`). Ex: `{{bundlebee-directory-json-key-value-pairs-content:resources/app/annotations/*.txt}}`.

If none of these placeholders match, then Microprofile Config is used to lookup the value (so system properties, environment variables and BundleBee args are used).

TIP: file placeholders can also read a resource from the classpath if the path does not match any existing file.

== Windows and CLI

On windows, the usage of the Java mode is recommended and the most reliable, however, if you want to speed up a bit the execution you can run the native bundlebee executable in a docker image.

TIP: ensure to test this solution *on your machine*, on our test machine gain can be x2 but it depends the docker setup too.

Once done you would be able to replace `bundlebee` by `docker run bundlebee -v $HOME/.kube/config:/kube/config -e KUBECONFIG=/kube/config --network host` (use an alias ;)).

Here are the step to use this solution:

. Download bundlebee native binary, for that go on https://repo.maven.apache.org/maven2/io/yupiik/bundlebee-core/, select the version you want and download the file ending with `Linux-amd64`,
. Create this `Dockerfile` file next to the binary you just downloaded and renamed `bundlebee`:
+
[source,dockerfile]
----
FROM ubuntu:20.10 as builder

RUN apt-get update && apt-get install -y zlib1g libgcc-s1 libstdc++6

FROM scratch

ENV LD_LIBRARY_PATH /lib

COPY --from=builder /lib/x86_64-linux-gnu/libc.so.6 /lib/libc.so.6
COPY --from=builder /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/libgcc_s.so.1
COPY --from=builder /lib/x86_64-linux-gnu/libstdc++.so.6.0.28 /lib/libstdc++.so.6
COPY --from=builder /lib/x86_64-linux-gnu/libpthread.so.0 /lib/libpthread.so.0
COPY --from=builder /lib/x86_64-linux-gnu/libdl.so.2 /lib/libdl.so.2
COPY --from=builder /lib/x86_64-linux-gnu/libm.so.6 /lib/libm.so.6
COPY --from=builder /lib/x86_64-linux-gnu/libz.so.1 /lib/libz.so.1
COPY --from=builder /lib64/ld-linux-x86-64.so.2 /lib/ld-linux

COPY bundlebee-core /bin/bundlebee-core

CMD ["/lib/ld-linux", "/bin/bundlebee-core"]
----
+
. Run `docker build -t bundlebee .` in the folder you put `bundlebee` binary and previous `Dockerfile`

IMPORTANT: this dockerfile works as of today because binaries are build on Ubuntu 20.10, you can need to adjust a bit libraries if this changes - this is why Java mode is simpler.

== Linting

Linting is quite specific so it has its own xref:linting.adoc[documentation].
