apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: bundlebee-plugin
spec:
  version: v1.0
  init:
    # if you use any kind of secret management, it can be neat to run a command there to decipher the secrets and prepare generate command
    command: [sh]
    args: [-c, 'echo "BundleBee plugin"']
  generate:
    command: [ "/opt/yupiik/bundlebee/bin/bundlebee.sh" ]
  discover:
    find:
      glob: "**/bundlebee/manifest.json"
  parameters:
    dynamic:
      command: [ "/opt/yupiik/bundlebee/bin/bundlebee.placeholders.sh" ]
    preserveFileMode: false
